name: flutter_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Philosopher
      fonts:
        - asset: fonts/Philosopher-Regular.ttf
        - asset: fonts/Philosopher-Italic.ttf
          style: italic
        - asset: fonts/Philosopher-Bold.ttf
          weight: 700
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
        - asset: fonts/NunitoSans_7pt-Bold.ttf
          weight: 700


